### ISSUE TITLE
need to generate video thumbnail in portrait mode

### ISSUE THREAD

**Issue by nikunjce** [mtebenev/MediaToolkit.NetCore#4]
Hi,

I am generating video thumbnail and it is working fine but when I tried to generate thumbnail of portrait video then it generates thumbnail in landscape mode.
can you please suggest me on this issue.

Thanks.

**Comment by mtebenev** [comment]
@nikunjce It looks like an issue related to the ffmpeg. Please try running ffmpeg with command line to generate the thumbnail and compare with the output from the library.

**Comment by nikunjce** [comment]
Yes there was a problem in ffmpeg.

**Comment by mtebenev** [comment]
Closing.
